<a href="https://colab.research.google.com/github/jamellasagelliv/linearpubfiles2021/blob/main/Assignment4_Villegas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra for ECE**

# **Laboratory 4: Matrices**

Now that you have a fundamental knowledge in Python, we'll try to look in greater dimwnsions.

**Objectives**

At the end of this activity you wil be able to:


1.   Be familiar with matrices and their relation to linear equation.
2.   Perform basic matrix operation.
3.  Program and translate matrix equation and operations using Python.




# **Discussion**

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

**Matrices**

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundred and thousand of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$ A = \left\{ \begin{array}\ x + y \\ 4x - 10y \end{array} \right. \\ B = \left\{ \begin{array}\ x+y+z \\ 3x -2y -z \\ -x + 4y +2z \end{array} \right. $$
We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$ A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\ B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} $$
So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$


**Declaring Matrices**

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&amp;a_{(0,1)}&amp;\dots&amp;a_{(0,j-1)}\\
a_{(1,0)}&amp;a_{(1,1)}&amp;\dots&amp;a_{(1,j-1)}\\
\vdots&amp;\vdots&amp;\ddots&amp;\vdots&amp;\\
a_{(i-1,0)}&amp;a_{(i-1,1)}&amp;\dots&amp;a_{(i-1,j-1)}
\end{bmatrix}
$$
We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

In [ ]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



# **Categorizing Matrices**

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.
 
## **According to shape**

**Row and Column Matrices** 

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [17]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



**Square Matrices**

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



# **According to element values**

**Null Matrix**

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [18]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



**Zero Matrix**

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [19]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Ones Matrix**

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [22]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


**Diagonal Matrix**

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

 **Identity Matrix**

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

 **Upper Triangular Matrix**

An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

**Lower Triangular Matrix**

A lower triangular matrix is a matrix that has no values above the diagonal.

In [20]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

# **Practice**



1.   Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [46]:
np.array([
    [3, 1, -4]
])

array([[ 3,  1, -4]])

Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

$$

G = \left\{
    \begin{array}\
        x_1 + 3x_2 + 2x_3\\ 
        1x_1 + 9x_2 + 7x_3\\
        8x_1 + 1x_2 + 3_3
    \end{array}
\right.$$

In [21]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])



1.   Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.




In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# **Matrix Algebra**

**Addition**

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

**Subtraction**

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])


**Element-wise Multiplication**

In [ ]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [41]:
A@B

array([[ 76,  68,  76],
       [108, 104, 124],
       [ 44,  52,  76]])

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

# **Activity**

## **Task 1**

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.

2. Displays whether the matrix is square or non-square.

3. Displays whether the matrix is an empty matrix.

4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

## **Function Area**

In [42]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

#### **Matrix Declaration**

In [33]:
A = np.array([
    [3, 5, 7],
    [5, 4, 6],
    [1, 4, 8]   
  ])
describe_mat(A)       

square_mat = np.array([
    [3,5,7],
    [5,4,6],
    [1,4,8]
])

non_square_mat = np.array([
    [3,5,7],
    [5,4,6]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

ones_mat_row = np.ones((3,5))
ones_mat_sqr = np.ones((5,4))
ones_mat_rct = np.ones((1,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Matrix:
[[3 5 7]
 [5 4 6]
 [1 4 8]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[3 5 7]
 [5 4 6]
 [1 4 8]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[3 5 7]
 [5 4 6]]

Shape:	(2, 3)
Rank:	2
Is Square: False

Ones Row Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]]


In [37]:
B = np.array([
    [1, 3, 5],
    [5, 5, 9],
    [9, 7, 5]   
  ])
describe_mat(B)       

square_mat = np.array([
    [1,3,5],
    [5,5,9],
    [9,7,5]
])

non_square_mat = np.array([
    [1,3,5],
    [5,5,9]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

ones_mat_row = np.ones((1,3))
ones_mat_sqr = np.ones((5,3))
ones_mat_rct = np.ones((9,7))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Matrix:
[[1 3 5]
 [5 5 9]
 [9 7 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 3 5]
 [5 5 9]
 [9 7 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 3 5]
 [5 5 9]]

Shape:	(2, 3)
Rank:	2
Is Square: False

Ones Row Matrix: 
[[1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [36]:
C = np.array([
    [2, 4, 6],
    [6, 6, 8],
    [6, 4, 2]   
  ])
describe_mat(C)       

square_mat = np.array([
    [2,4,6],
    [6,6,8],
    [6,4,2]
])

non_square_mat = np.array([
    [2,4,6],
    [6,6,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

ones_mat_row = np.ones((2,4))
ones_mat_sqr = np.ones((6,6))
ones_mat_rct = np.ones((6,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Matrix:
[[2 4 6]
 [6 6 8]
 [6 4 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 4 6]
 [6 6 8]
 [6 4 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 4 6]
 [6 6 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False

Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
D = np.array([
    [2, 2, 2],
    [4, 4, 4],
    [8, 8, 8]   
  ])
describe_mat(D)       

square_mat = np.array([
    [2,2,2],
    [4,4,4],
    [8,8,8]
])

non_square_mat = np.array([
    [2,2,2],
    [4,4,4]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

ones_mat_row = np.ones((2,2))
ones_mat_sqr = np.ones((4,4))
ones_mat_rct = np.ones((8,8))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Matrix:
[[2 2 2]
 [4 4 4]
 [8 8 8]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 2 2]
 [4 4 4]
 [8 8 8]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 2 2]
 [4 4 4]]

Shape:	(2, 3)
Rank:	2
Is Square: False

Ones Row Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
E = np.array([
    [3, 3, 3],
    [6, 6, 6],
    [9, 9, 9]   
  ])
describe_mat(E)       

square_mat = np.array([
    [3,3,3],
    [6,6,6],
    [9,9,9]
])

non_square_mat = np.array([
    [3,3,3],
    [6,6,6]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

ones_mat_row = np.ones((3,3))
ones_mat_sqr = np.ones((6,6))
ones_mat_rct = np.ones((9,9))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Matrix:
[[3 3 3]
 [6 6 6]
 [9 9 9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[3 3 3]
 [6 6 6]
 [9 9 9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[3 3 3]
 [6 6 6]]

Shape:	(2, 3)
Rank:	2
Is Square: False

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### **Test Areas**

In [43]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [44]:
## Zero Matrix
desc_mat(zero_mat_sqr)

Matrix:
[[0. 0.]
 [0. 0.]]

Shape:	(2, 2)
Rank:	2



In [47]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Shape:	(6, 6)
Rank:	2



## **Task 2**

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.

1. Returns the sum of the matrices.

2. Returns the differen of the matrices.

3. Returns the element-wise multiplication of the matrices.

4. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

#### **Function Area**

In [50]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

#### **Matrix Declaration**

In [52]:
## Addition
A = np.array([
    [2,2,3],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [2,5,9],
    [6,3,7],
    [1,3,4]
])

In [53]:
## Subtraction
D = np.array([
    [2,8,9],
    [6,2,3],
    [7,4,0]
])
E = np.array([
    [6,9,4],
    [4,3,3],
    [3,2,1]
])

In [ ]:
## element-wise multiplication
F = np.array([
    [1,9,5],
    [5,3,3],
    [1,2,7]
])
G = np.array([
    [5,6,5],
    [2,9,8],
    [1,1,2]
])

In [54]:
## element-wise division
H = np.array([
    [14,11,17],
    [12,17,5],
    [15,11,13]
])
I = np.array([
    [1,3,5],
    [3,6,9],
    [10,1,2]
])

#### **Test Areas**

In [59]:
## Addition
H = A+D
mat_operations(C)

Matrix:
[[ 4 10 12]
 [10  7  9]
 [14 12  9]]

Shape:	(3, 3)
Rank:	2



In [57]:
np.add(A,D)

array([[ 4, 10, 12],
       [10,  7,  9],
       [14, 12,  9]])

In [60]:
## Subtraction
I = E-D
mat_operations(S)

Matrix:
[[ 4  1 -5]
 [-2  1  0]
 [-4 -2  1]]

Shape:	(3, 3)
Rank:	2



In [68]:
np.subtract(E,D)

array([[ 4,  1, -5],
       [-2,  1,  0],
       [-4, -2,  1]])

In [74]:
## element-wise multiplication
J = A*G
mat_operations(M)

Matrix:
[[ 2 14 24]
 [ 8 10 12]
 [28 48 63]]

Shape:	(3, 3)
Rank:	2



In [72]:
np.multiply(A,G)

array([[ 2, 14, 24],
       [ 8, 10, 12],
       [28, 48, 63]])

In [73]:
2*G

array([[ 2, 14, 16],
       [ 4,  4,  4],
       [ 8, 12, 14]])

In [76]:
## element-wise division
K = B/C
mat_operations(K)

Matrix:
[[0.5        0.5        0.75      ]
 [0.6        0.42857143 0.77777778]
 [0.07142857 0.25       0.44444444]]

Shape:	(3, 3)
Rank:	2



In [77]:
np.divide(B,C)

array([[0.5       , 0.5       , 0.75      ],
       [0.6       , 0.42857143, 0.77777778],
       [0.07142857, 0.25      , 0.44444444]])

In [78]:
B/5

array([[0.4, 1. , 1.8],
       [1.2, 0.6, 1.4],
       [0.2, 0.6, 0.8]])

In [79]:
3/C

array([[0.75      , 0.3       , 0.25      ],
       [0.3       , 0.42857143, 0.33333333],
       [0.21428571, 0.25      , 0.33333333]])

## **Conclusion**

In this laboratory activity, there are added functions like shape and rank that are just like the continuation of the previous laboratory activity. Some of the Arithmetic functions that have been discussed in this laboratory are more elaborated than before. It's like every activity that has been discussed is just a continuation of the previous activity, and it's a good thing that it is a simple step to understand more about how to use the Python language.